server:
  port: 10000
spring:
  application:
    name: itrip-search-consumer
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka