### 配置项目启动端口号
server:
  port: 7777
spring:
  ### 项目应用名
  application:
    name: itrip-auth-consumer
### 配置Eureka Client相关信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/